In [7]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

x = iris.data
y = iris.target

In [3]:
print(x.shape)

(150, 4)


In [4]:
print(y.shape)

(150,)


In [5]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [9]:
print(x_train.shape)

(120, 4)


In [10]:
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(120,)
(30, 4)
(30,)


# KNN

In [45]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [46]:
data = pd.read_csv('car.data')

In [47]:
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [48]:
x = data[[
    'buying',
    'maint',
    'safety'
]].values
y = data[['class']]
print(x,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [49]:
# conversion for ml model
# converting data
le = LabelEncoder()
for i in range(len(x[0])):
    x[:,i] = le.fit_transform(x[:,i])
print(x)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [50]:
# converting y
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)


[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-50-60221a8a1dd3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [51]:
# creat model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

knn.fit(x_train, y_train)

prediction = knn.predict(x_test)

accuracy = metrics.accuracy_score(y_test, prediction)
print("Prediction : ", prediction)
print("Accuracy: ", accuracy)

Prediction :  [0 0 0 0 1 0 1 0 0 0 0 0 1 0 3 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 3 1 3 1 0 1 3
 1 0 1 0 2 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 3 1 0 0 0 0 1 0 0 0 0 1 0 3 0 0
 0 0 0 0 0 0 3 1 0 0 0 3 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 2 1 0 0 0
 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 2 0 0 0 0 0 0 0 0 2 1 0 3 0 1
 0 0 0 0 1 0 1 0 1 3 0 0 0 0 2 1 1 0 1 3 0 0 0 3 0 0 1 2 3 0 0 0 0 1 2 2 0
 0 3 3 0 0 0 0 0 0 0 1 1 0 3 2 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 2 0 0
 0 1 0 0 0 1 0 0 3 0 1 0 1 3 0 0 0 3 0 0 0 1 0 0 0 0 0 1 0 0 0 2 1 0 3 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 2 0 0 0 0 1 0 0 1 0 3 3 1 3
 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 2 0 3 0 0 0 1 0 0 1 0 0 0
 0 0 0 1 0 2 3 0 0 0 0 0 1]
Accuracy:  0.7485549132947977


<ipython-input-51-f26b27301843>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)


In [52]:
# testing model
print("Actual value: ",y[20])
print("Predicted value: ", knn.predict(x)[20])

Actual value:  [0]
Predicted value:  0


In [53]:
a=1727
print("Actual value: ",y[a])
print("Predicted value: ", knn.predict(x)[a])

Actual value:  [3]
Predicted value:  3


In [54]:
a=1723
print("Actual value: ",y[a])
print("Predicted value: ", knn.predict(x)[a])

Actual value:  [2]
Predicted value:  2


In [55]:
a=1725
print("Actual value: ",y[a])
print("Predicted value: ", knn.predict(x)[a])

Actual value:  [0]
Predicted value:  0


In [56]:
a=172
print("Actual value: ",y[a])
print("Predicted value: ", knn.predict(x)[a])

Actual value:  [0]
Predicted value:  0


In [58]:
a=1111
print("Actual value: ",y[a])
print("Predicted value: ", knn.predict(x)[a])

Actual value:  [0]
Predicted value:  1
